# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/hyprlock.png
    blur_passes = 0
}

animations {
    enabled = false
}

# GENERAL
general {
    grace = 0
    disable_loading_bar = true
}

# USER-TEXT
label {
    monitor =
    text = login :
    color = #abb2bf
    font_size = 17
    font_family = monospace
    position = -180, 25
    halign = center
    valign = center
}

# USER-NAME
label {
    monitor =
    text = $USER
    color = #abb2bf
    font_size = 17
    font_family = monospace
    position = 0, 25
    halign = center
    valign = center
}


# PASSWORD-TEXT
label {
    monitor =
    text = password :
    color = #abb2bf
    font_size = 17
    font_family = monospace
    position = -200, -25
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 40
    rounding = 0
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(86, 90, 90, 1)
    inner_color = rgba(40, 40, 40, 1)
    font_color = monospace
    fade_on_empty = false
    font_family = monospace
    placeholder_text = <i><span foreground="##ffffff99"></span></i>
    hide_input = false
    position = 0, -25
    halign = center
    valign = center
}
