
# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bindd = $mainMod, space, Open terminal, exec, $terminal
bindd = $mainMod, Q, Quit active window, killactive,

bindd = $mainMod, H, Shortcuts,  exec, okpanel shortcuts
bindd = $mainMod, SUPER_L, App launcher, exec, pkill tofi-run || tofi-run | xargs hyprctl dispatch exec --

bindd = $mainMod, J, Toggle split between horozntal and vertical, togglesplit, # dwindle

# Move focus with mainMod + arrow keys
bindd = $mainMod, left, Focus left, movefocus, l
bindd = $mainMod, right, Focus right, movefocus, r
bindd = $mainMod, up, Focus up, movefocus, u
bindd = $mainMod, down, Focus down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bindd = $mainMod, 1, Switch to workspace 1, workspace, 1
bindd = $mainMod, 2, Switch to workspace 2, workspace, 2
bindd = $mainMod, 3, Switch to workspace 3, workspace, 3
bindd = $mainMod, 4, Switch to workspace 4, workspace, 4
bindd = $mainMod, 5, Switch to workspace 5, workspace, 5

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bindd = $mainMod ALT, 1, Move window to workspace 1, movetoworkspace, 1
bindd = $mainMod ALT, 2, Move window to workspace 2, movetoworkspace, 2
bindd = $mainMod ALT, 3, Move window to workspace 3, movetoworkspace, 3
bindd = $mainMod ALT, 4, Move window to workspace 4, movetoworkspace, 4
bindd = $mainMod ALT, 5, Move window to workspace 5, movetoworkspace, 5

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
