wallpaperUpdateScript = ${HOME}/provision/set_wallpaper.sh
scrimColor            = #00000010

systemCommands {
    logout   = hyprctl dispatch exit
    lock     = hyprlock
    restart  = systemctl reboot
    shutdown = systemctl poweroff
}

themes = [
    ${theme_list}
] 
