keybindingsFile   = $HOME/.config/hypr/keybindings.conf
themeUpdateScript = $HOME/.local/bin/theme
wallpaperUpdateScript = $HOME/.local/bin/set-wallpaper
scrimColor            = #00000010

systemCommands {
    logout   = hyprctl dispatch exit
    lock     = hyprlock
    restart  = systemctl reboot
    shutdown = systemctl poweroff
}

themes = [
    ${theme_list}
] 
